# Generated by Django 3.0.7 on 2020-07-01 06:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_type', models.CharField(choices=[('F', 'Faculty'), ('C', 'Club'), ('N', 'Not Assigned')], default='N', max_length=1)),
                ('workplace', models.CharField(default='Not Known', max_length=255)),
                ('password_reset_token', models.BigIntegerField(blank=True, null=True)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
